name: MagicPlugin
version: ${project.version}
main: com.github.ukraine1449.magicplugin.MagicPlugin
api-version: 1.16
authors: [ Ukraine1449 ]
description: A plugin to use magic tools and weapons
website: plugins.world
commands:
  hammer:
    description: gives you the "Fuck you" hammer
    permission: Magic.hammer
  shield:
    description: gives you the shield of darknesss
  bow:
    description: gives you Cupids bow
  EH:
    description: Helmet that lets you see people within 10 blocks
  shears:
    description: gives you the shears of head cutting
  scythe:
    description: gives you deaths scythe
  boombow:
    description: gives you a bow which explodes stuff
  invis:
    description: Gives invisibility armor
  zeus:
    description: Gives you zeuses bow
  BoomStick:
    description: Gives you an explosive stick
  Vest:
    description: gives you the suicide bomber vest
  vestBig:
    description: A bigger suicide bomber vest
  boots:
    description: gives you slow falling boots
  pickaxe:
    description: Gives you an explosive pickaxe
  slowStick:
    description: gives you stick to make people slow
  wings:
    description: gives you wings
  tpbow:
    description: teleports you to wherever you hit
  tshield:
    description: A temporary supershield